basePath: /
host: localhost:8080
info:
  contact:
    email: me@me.com
    name: Me
    url: http://me.com/terms.html
  description: Sample CRUD api for agency_portal db
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Sample CRUD api for agency_portal db
  version: "1.0"
paths: {}
swagger: "2.0"
